#!/bin/bash
# Orignal Author: 2007, by Robert Manea Date
# Modified by:  https://github.com/mohabaks  Wed 25 Oct 2017
# Description: A simple popup calendar using dzen2
#

# Source colors
#. $HOME/.local/bin/color-parser
. $HOME/.cache/wal/colors.sh

TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
LINES=$(cal -m | wc -l)
LINES=$((LINES + 1))

(
#date +'%A, %d %b %Y %H:%M'
date +'^bg(#00000000) '
date +''

#n30f -d -x 0 -y 0 $HOME/.config/popups/calendar/bg.png &
# current month, highlight header and today
cal -m | sed -r -e "1,2 s/.*/^fg($color1)&^fg()/"  -e "s/(^| )($TODAY)($|)/\1^bg($color1)^fg($color0)\2^fg()^bg()\3/") | dzen2 -fn "DejaVu Sans Mono:pixelsize=13" -x 830 -y 0 -w 250 -h 20 -l $LINES -tw 0 -sa c -p -e 'onstart=uncollapse,hide;button1=exit;' -fg "$color6" -bg "$background"

pkill n30f
